"""Varshaphal (annual chart): Muntha + Mudda-dasha bhava data.

Split out of the former 1895-line kundli_data.py god-module (data only).
Re-exported via kundli_data/__init__.py so imports are unchanged."""



# ── VARSHAPHAL — Muntha by Bhava (12 entries) ──────────────────────────────
# Muntha is a sensitive point in Tajik (annual) astrology that advances one
# sign per completed year of age, starting from the natal Lagna. Its bhava
# placement in the annual chart frames the dominant theme of the year.

MUNTHA_HOUSE_DATA = {
    1: "Muntha in 1st Bhav: A year focused squarely on yourself — health, identity, and personal initiatives take centre stage. New beginnings are favoured, and your willpower runs strong. Watch for impulsive decisions and pay attention to physical well-being, especially the head and face.",
    2: "Muntha in 2nd Bhav: Wealth, family matters, and your manner of speech come into focus this year. There may be steady financial accumulation and improved standing within the family, though arguments at home can flare up. Be mindful with your words; what you say carries unusual weight now.",
    3: "Muntha in 3rd Bhav: Courage, communication, and relationships with siblings dominate the year. You may take bold initiatives, undertake short journeys, and assert yourself more than usual. Writing, marketing, or any work that depends on your voice tends to do well.",
    4: "Muntha in 4th Bhav: Home, mother, and emotional security become the central themes. Property matters, vehicle changes, or a renovation of your living space are likely. Inner peace depends on resolving domestic issues — buried family tensions may rise to the surface for healing.",
    5: "Muntha in 5th Bhav: A creative, romantic, and intellectually rich year. Children, love affairs, learning, and speculative pursuits flourish. Avoid reckless gambling and overconfidence in investments. This is a good year to teach, study, or create.",
    6: "Muntha in 6th Bhav: Service, struggles, and overcoming opponents define the year. You may face debts, health challenges, or workplace conflicts, but you also gain the strength to overcome them. Discipline in diet and routine pays off; competitive endeavours go in your favour.",
    7: "Muntha in 7th Bhav: Partnerships — marital, business, or public — take centre stage. Marriage, contracts, or major collaborations are highly likely. Foreign travel and dealings with strangers increase. Mind your dealings with the spouse; harmony or friction here will colour the whole year.",
    8: "Muntha in 8th Bhav: A year of transformation, hidden matters, and unexpected change. Inheritance, insurance, occult studies, or research may bring gains, but sudden losses, surgery, or psychological turbulence can also surface. Approach the year with introspection rather than aggression.",
    9: "Muntha in 9th Bhav: Luck, dharma, higher learning, and long journeys come to the fore. Pilgrimages, spiritual study, university work, or interactions with mentors and gurus go well. Father-related matters and legal affairs see resolution. Generally one of the most fortunate Muntha placements.",
    10: "Muntha in 10th Bhav: Career, status, and public recognition are the year's defining themes. Promotion, professional change, or increased authority is likely, often coupled with extra responsibility. Reputation matters more than ever — guard against actions that could damage your standing.",
    11: "Muntha in 11th Bhav: Gains, fulfilled desires, and expanded social networks mark the year. Income tends to rise, friendships deepen, and long-pending wishes find resolution. Excellent for joining groups, launching networked ventures, or harvesting investments made earlier.",
    12: "Muntha in 12th Bhav: A year tilted toward expenses, foreign matters, spirituality, and behind-the-scenes work. Expect higher outflows, possible relocation or travel abroad, and a pull toward solitude or meditation. Hidden enemies may emerge — keep your plans private and focus on inner growth.",
}


# ── VARSHAPHAL — Mudda Dasha lord × Bhava (9 × 12 = 108 entries) ───────────
# During Varshaphal (annual horoscope), the Mudda Dasha sub-period predictions
# depend on the dasha lord's house placement in the ANNUAL chart (cast at the
# solar return), not the natal chart. Lookup:
# MUDDA_DASHA_BHAV_DATA[planet][bhav_number] → paragraph string.

MUDDA_DASHA_BHAV_DATA = {
    "Sun": {
        1: "Sun in Bhav 1 during this period: your vitality and personal authority will rise sharply, drawing attention from superiors and peers alike. Career visibility improves and people will look to you for direction, though pride or ego could strain a close relationship. Watch your blood pressure and eyes; favor light food and morning sun. A good window to launch a personal brand or step into a leadership role.",
        2: "Sun in Bhav 2 during this period: focus shifts to money, family standing and the words you choose. You may receive a salary hike, bonus or recognition through family lineage, but spending on status symbols can climb just as quickly. Speak with measured authority — harsh speech now creates lasting friction. Take care of teeth, throat and right eye; small dental or vision issues are best addressed early.",
        3: "Sun in Bhav 3 during this period: courage, initiative and short journeys define the months ahead. You will push past hesitation, take calculated risks, and possibly take charge of a sibling or younger colleague's situation. Communication and self-promotion go well, especially in writing or public speaking. Avoid overexertion of arms and shoulders; channel the surplus energy into structured exercise rather than impulsive arguments.",
        4: "Sun in Bhav 4 during this period: home and mother become the stage. There may be renovations, a vehicle purchase, or relocation tied to work, alongside some friction with elders over decisions. Emotional comfort can dip even as material comfort grows; carve out quiet evenings. Property matters favor formal agreements signed in daylight, and a long-pending domestic issue can finally be cleared with directness.",
        5: "Sun in Bhav 5 during this period: creativity, children and learning come into focus. Students perform well in exams and competitive selections; parents may celebrate a milestone for a child. Speculative gains are possible but volatile — keep position sizes small. A romantic relationship gains seriousness or, if already strained, faces a frank reckoning. Devotional practice and study of classical subjects feel especially rewarding now.",
        6: "Sun in Bhav 6 during this period: a strong year for defeating opponents, clearing debts and recovering from chronic complaints. Workload at the office rises but so does your standing among colleagues; expect a promotion or expanded responsibility. Legal and disciplinary matters tilt in your favor if you act with integrity. Guard against acidity, fevers and inflammation; routine matters more than intensity in workouts.",
        7: "Sun in Bhav 7 during this period: partnerships — marital and business — take centre stage and demand your direct engagement. A spouse or partner may seek more autonomy, or your own ego could clash with theirs; honest conversation prevents drift. Public dealings, contracts and travel for collaboration are favored. Avoid signing under pressure; let the other side reveal their hand first. Health of the partner deserves attention.",
        8: "Sun in Bhav 8 during this period: transformation, inheritance and hidden matters surface. You may receive ancestral money, insurance settlement or a sudden positional shift, but bureaucratic delays are likely. Research, occult studies and deep introspection bring genuine breakthroughs. Take father's health seriously and avoid risky travel or extreme sports. Old secrets — yours or others' — could come to light, so handle disclosures with care.",
        9: "Sun in Bhav 9 during this period: dharma, mentors and long journeys bless the year. You will feel pulled toward higher learning, pilgrimage or a new philosophical framework, and a senior figure may open doors that effort alone could not. Foreign travel for work or study is well-aspected. Father-related news tends to be significant. Teaching, publishing and ethical leadership all bring tangible rewards now.",
        10: "Sun in Bhav 10 during this period: one of the most powerful placements for career advancement. Recognition from authorities, government dealings, promotion or public success becomes very likely if you have prepared the ground. Work hours grow long and family time shrinks, so guard the balance. Reputation is your real asset this year — protect it from any shortcut. Honors, awards or media attention are realistically within reach.",
        11: "Sun in Bhav 11 during this period: gains, network and elder sibling matters dominate. Income from primary source rises, and influential friends actively support your goals. A long-held wish moves visibly closer. Be selective about which circles you join; one wrong alliance can dim your light. Recognition within professional bodies, clubs or associations is likely, and group leadership roles may land in your lap.",
        12: "Sun in Bhav 12 during this period: expenses, foreign matters and inner life come forward. Spending on travel, charity, medical care or a parent can climb, and visibility at work may temporarily reduce as you handle behind-the-scenes work. Sleep, eyes and overall vitality need protection — avoid late nights. A retreat, solo trip or quiet spiritual practice will restore you more than any social effort could.",
    },
    "Moon": {
        1: "Moon in Bhav 1 during this period: emotions colour everything you do, for better and worse. You become more approachable, intuitive and well-liked, and women in your circle play a supportive role. Mood swings are likely, so anchor yourself with sleep, water and a steady morning routine. Travel near water is enjoyable. Public-facing or creative work flourishes, but avoid making major decisions on a low-energy day.",
        2: "Moon in Bhav 2 during this period: family bonds, food and finances dominate. Income flows steadily, often through nurturing roles, hospitality or work connected to women. Speech becomes softer and more persuasive — useful in negotiations. Guard against emotional eating and impulse purchases. A family gathering, wedding or ritual is likely, and your maternal side of the family may feature prominently in good news.",
        3: "Moon in Bhav 3 during this period: short trips, siblings and creative communication lift your year. Writing, music and content work attract a warm response, and a sister or close friend offers timely support. Courage is moderate rather than fiery — you will act when comfortable, not before. Watch overthinking before bed. A new skill picked up casually now can become genuinely useful within months.",
        4: "Moon in Bhav 4 during this period: one of the most comforting placements. Home life is harmonious, mother's well-being improves, and you may upgrade your living space or vehicle. Emotional security feels restored after recent strain. Real estate dealings are favorable, especially properties near water. Avoid overattachment to past grievances; the year rewards softness over stubbornness, and a long-cherished domestic plan finally takes shape.",
        5: "Moon in Bhav 5 during this period: romance, children and creative joy bloom. Conception or news of a child is possible for those trying; existing children bring genuine pride. Studies, especially in arts or counselling, go well. Light speculation can pay off but stay modest. You will feel more romantic and playful than usual — a good year to invest in a relationship rather than test it.",
        6: "Moon in Bhav 6 during this period: emotional ups and downs at work and minor recurring health issues need attention. You may take on caregiving for a relative or pet, which is meaningful but draining. Debts can be repaid steadily; new loans should be avoided. Female colleagues or clients prove allies. Watch digestion, sleep and anxiety; gentle routines outperform intense interventions this year.",
        7: "Moon in Bhav 7 during this period: partnerships become more emotionally rich. Spouse's mood and well-being shape the household tone, and a single person may meet someone significant through social or family channels. Business partnerships with women are favored. Public dealings go smoothly when you lead with empathy. Avoid moodiness in negotiations — clarity now prevents misunderstandings that could echo for months.",
        8: "Moon in Bhav 8 during this period: emotional intensity, dreams and hidden matters surface. You may handle a sensitive family secret, an inheritance, or a deep psychological shift. Mother's health deserves a check-up. Avoid water-based adventures and risky travel. Healing modalities, therapy and journaling work especially well now, and a fear you have carried for years can finally lose its grip.",
        9: "Moon in Bhav 9 during this period: long travels, often connected with family, mother or pilgrimage, become a highlight. Faith deepens through experience rather than argument, and a teacher or elder offers exactly the perspective you need. Studies abroad or remote learning programs are favored. Publishing, teaching and culturally-rooted work attract attention. A trip to a riverside or coastal sacred site would be deeply restorative.",
        10: "Moon in Bhav 10 during this period: career gains a public, people-facing dimension. Roles in hospitality, healthcare, food, media or care work flourish, and women in authority support your rise. Reputation grows through warmth rather than aggression. Some changes in workplace or role are likely; ride the wave instead of resisting. Mother may take pride in a public milestone you achieve this year.",
        11: "Moon in Bhav 11 during this period: friends, networks and steady gains brighten the year. Income from multiple small streams adds up, and a long-held emotional wish — often related to family — gets fulfilled. Female friends are particularly supportive. Group activities, communities and clubs become a source of joy. Be selective with new acquaintances; not every warm face deserves your full trust just yet.",
        12: "Moon in Bhav 12 during this period: inner life, sleep and foreign matters come into focus. You may travel abroad, spend on a parent's care, or withdraw socially to recharge. Dreams become vivid and meaningful. Meditation, art and time near water heal more than any new venture would. Watch tendency toward melancholy; a small daily routine of light, movement and music keeps the mood steady.",
    },
    "Mars": {
        1: "Mars in Bhav 1 during this period: energy, courage and physical drive surge. You will push initiatives that have been stalled and may take a bold personal stand. Anger flares quickly though, and accidents, cuts or fevers are possible — channel the heat into exercise. Confidence is magnetic and others fall in line. A good window to start something demanding, provided you don't bulldoze the relationships around you.",
        2: "Mars in Bhav 2 during this period: finances and speech both heat up. Income can rise through bold action, but harsh words risk damaging family ties. Avoid lending money and signing under pressure. Dental work, throat issues or eye strain may need attention. Family conflicts over property or inheritance are possible; address them with facts rather than emotion. Disciplined budgeting protects the year's gains.",
        3: "Mars in Bhav 3 during this period: arguably one of Mars's best placements. Courage soars, initiatives succeed, and short trips bring tangible results. Relationships with siblings — especially younger ones — turn dynamic; some friction is possible, but so is genuine teamwork. Sales, sports, military and entrepreneurial efforts thrive. Hands, arms and shoulders need care during workouts. Self-promotion that felt awkward before now feels natural.",
        4: "Mars in Bhav 4 during this period: tensions at home and possible property disputes. A need to act decisively about your living situation arises; renovation, relocation or a vehicle change is likely. Mother's health and peace of mind deserve attention. Physical exertion pays off, but burning the candle too hard invites minor accidents. Resist slamming doors — both literal and metaphorical — when negotiations get heated.",
        5: "Mars in Bhav 5 during this period: passion, competition and risk dominate. Speculative ventures can win or lose big; small position sizes are wise. Children may be more headstrong than usual, especially sons. Romance is intense but argumentative. Sports, competitive exams and creative pitches do well. A miscarriage risk exists for couples expecting; medical caution and rest are essential during the early months.",
        6: "Mars in Bhav 6 during this period: excellent for defeating enemies, winning lawsuits and clearing debts. Workplace rivals retreat once you confront them clearly. Surgeries, if needed, succeed. Watch for inflammation, fevers, blood-related issues and accidents with sharp tools. Service-oriented roles, military, police and emergency work thrive. Loans can be repaid faster than expected; resist the urge to take on new ones for status reasons.",
        7: "Mars in Bhav 7 during this period: partnerships and marriage feel charged. Arguments with spouse or business partner are likely, and a power struggle may surface. Direct dialogue settles it; silence makes it fester. Public dealings demand restraint. Single people may meet someone fiery and attractive but volatile. Health of the partner needs attention. Travel for partnership matters is likely and largely productive.",
        8: "Mars in Bhav 8 during this period: a sensitive placement requiring care. Risk of accidents, surgeries or sudden financial shocks rises; insurance and medical check-ups are wise. Research, investigation and occult work bring breakthroughs. Inheritance or partner's money may come with disputes attached. Avoid risky travel, extreme sports and confrontations with strangers. Deep transformation is offered if you face fears squarely instead of reacting.",
        9: "Mars in Bhav 9 during this period: a fighter's faith and bold journeys. You will defend your principles publicly, possibly travel to challenging destinations and take initiative in higher learning or publishing. A guru or mentor may push you firmly out of your comfort zone. Father's energy or health may be intense. Legal matters tied to property abroad can move forward. Avoid religious arguments — not every battle is yours.",
        10: "Mars in Bhav 10 during this period: career action and visible achievement. Promotions through bold execution, project leadership and competitive wins are very likely. Government, defense, engineering and entrepreneurial roles flourish. Workplace politics heats up; pick battles carefully. Long hours could strain home life. Reputation grows fast, but so do enemies of progress; document decisions and keep a paper trail to protect what you build.",
        11: "Mars in Bhav 11 during this period: powerful gains, especially through your own initiative. Income spikes through new ventures, sales or commissions, and influential allies join your cause. Elder sibling matters take a positive turn. Group leadership roles open up. Be cautious with who you bring into business; one impulsive partnership choice can leak the year's profits. Fitness goals and competitive sports also reward effort.",
        12: "Mars in Bhav 12 during this period: hidden enemies, expenses and foreign matters rise. Spending on litigation, medical care or a parent can spike. Sleep is disturbed; fiery dreams and restlessness need outlets like exercise and breathwork. A foreign trip or relocation for work is possible. Avoid impulsive decisions made in frustration. Solitary practice — gym, martial arts, meditation — channels the energy more cleanly than confrontation.",
    },
    "Mercury": {
        1: "Mercury in Bhav 1 during this period: intellect, wit and communication shine. You will think faster, write better and connect new dots in your work. Networking comes easily, and a youthful energy returns to your demeanor. Skin and nervous system can feel sensitive — moderate caffeine and screen time. A good year to study, publish, pitch ideas, or rebrand yourself professionally. Avoid overcommitting just because everything feels possible.",
        2: "Mercury in Bhav 2 during this period: a strong year for finances through skill, communication and trade. Income rises through writing, speaking, teaching, accounting or commerce. Family discussions become more rational and less heated. Watch for overpromising in speech; words are contracts now. Investments in stocks, mutual funds or short-term instruments perform well with research-backed picks. Light, varied food suits your constitution this year.",
        3: "Mercury in Bhav 3 during this period: an outstanding placement for writers, marketers, content creators and entrepreneurs. Short journeys multiply, ideas convert into projects quickly, and a sibling or peer becomes a key collaborator. Skill-building courses pay off rapidly. Hands, fingers and breathing deserve some care from screen overuse. Self-publishing, podcasts, newsletters or any communication-driven side venture launched now can gain real momentum.",
        4: "Mercury in Bhav 4 during this period: home life intellectualizes — conversations replace silences, and you may set up a study, library or remote-work corner. Vehicle, gadget or property purchases tied to communication are likely. Mother's health is generally fine but mental restlessness needs care. Real estate negotiations favor the well-prepared. A move or renovation focused on creating a calmer, more functional space brings lasting value.",
        5: "Mercury in Bhav 5 during this period: students, writers, traders and creators thrive. Exams, certifications and competitive selections go well with disciplined study. Children's education progresses; you may invest in tutoring or creative classes for them. Romance becomes witty and conversational. Speculation can pay if research-led, but avoid tips and rumors. Mantra practice or learning a sacred text adds an unexpected steadiness to the year.",
        6: "Mercury in Bhav 6 during this period: detail-oriented work, service roles and analytical problem-solving bring success. Debts can be cleared through careful planning, and lawsuits favor the side with better documentation — usually you. Watch nervous-system issues, skin allergies and digestion. Workplace disputes resolve through correspondence rather than confrontation. A pet may bring joy or require care. Routine, lists and process give you an edge this year.",
        7: "Mercury in Bhav 7 during this period: partnerships work best when communication is frequent and clear. Contracts, negotiations and joint ventures move forward smoothly. Spouse may pursue learning, writing or business ventures of their own. Singles may meet a partner who is articulate, witty or younger. Travel for partnerships is likely. Read the fine print on every agreement; small clauses missed now create big issues later.",
        8: "Mercury in Bhav 8 during this period: research, investigation, occult studies and analytical depth bring rewards. Inheritance or partner's money may involve paperwork — handle it meticulously. Hidden information surfaces and you become the one who pieces it together. Watch for nervous strain, anxiety and skin issues. Therapy, journaling and breathwork are deeply helpful. Avoid signing financial documents in a hurry, especially loans or insurance contracts.",
        9: "Mercury in Bhav 9 during this period: higher education, publishing and travel for learning shine. You may enroll in a course, write a thesis, or start a teaching role. Travel to foreign destinations for study or business is favored. Mentors are often younger or more nimble than expected. Legal matters move forward through documentation. Faith deepens through reading and discussion rather than ritual alone this year.",
        10: "Mercury in Bhav 10 during this period: career growth through skill, communication and intellect. Roles in writing, marketing, IT, finance, education, consulting and trade flourish. Public speaking, presentations and proposals open new doors. Reputation grows for being the clear thinker in the room. Workload is high but manageable with good systems. A career pivot toward a more knowledge-driven role is realistically on the table.",
        11: "Mercury in Bhav 11 during this period: gains through networking, technology, trade and intellectual peers. Income rises through multiple streams, often involving communication or skill-sharing. Younger friends and online communities become especially valuable. A long-held goal centered on knowledge, publishing or a side business gets fulfilled. Avoid over-talking your plans before they materialize — keep some cards close while building credibility steadily.",
        12: "Mercury in Bhav 12 during this period: behind-the-scenes work, foreign clients and inner study come forward. Writing in solitude, research, translation or work for overseas clients can flourish. Expenses on books, courses or technology rise. Watch nervous exhaustion, sleep and anxiety; reduce input and create thinking space. A foreign opportunity may arrive quietly through email or referral; respond promptly even if it seems small at first.",
    },
    "Jupiter": {
        1: "Jupiter in Bhav 1 during this period: one of the most fortunate placements. Wisdom, optimism and a sense of purpose return. Health improves, weight may climb gently, and people instinctively trust your judgement. A spiritual teacher, mentor or significant book enters your life. A good year to teach, marry, conceive, or start a long-term project; the universe seems to clear obstacles you used to find paralyzing.",
        2: "Jupiter in Bhav 2 during this period: family wealth, savings and speech all expand. Income grows through ethical means, often with a teaching, advisory or financial flavor. Family events — marriage, naming ceremony, religious gathering — are likely. Speech becomes more authoritative and people listen. Watch weight and sugar, as Jupiter can be generous with both. A long-pending family matter resolves through a wise elder's intervention.",
        3: "Jupiter in Bhav 3 during this period: courage tempered with wisdom. You will take initiatives that are bold yet considered, and a sibling may become a genuine ally. Short pilgrimages and educational trips are favored. Writing, teaching and publishing efforts go well. Self-promotion with substance behind it works better than flash. A mentorship role offered to you now can shape your reputation for years to come.",
        4: "Jupiter in Bhav 4 during this period: deeply auspicious for home, mother and inner peace. Property purchase, vehicle upgrade or home renovation is highly favored. Mother's health and happiness improve, and family bonds strengthen. Spiritual practice at home becomes natural. A long-cherished dream of owning a particular kind of space can materialize. Real estate transactions tend to favor you, especially if linked to family heritage.",
        5: "Jupiter in Bhav 5 during this period: children, learning and creativity flourish. Conception or birth of a child is highly favored, especially for those trying. Existing children achieve milestones that bring pride. Higher studies, teaching and creative pursuits succeed. Romance becomes meaningful rather than merely fun. Speculative gains are possible with restraint. Mantra, study of scripture and devotional practice yield unusually deep results this year.",
        6: "Jupiter in Bhav 6 during this period: a calm year for handling enemies, debts and disease. Conflicts dissolve through dialogue rather than escalation, lawsuits favor your side, and chronic conditions improve with the right practitioner. Workplace rivals lose interest. Some weight gain or liver-related care may be needed. Service to elders, animals or those in need brings unexpected blessings — and quietly transforms how you see your own difficulties.",
        7: "Jupiter in Bhav 7 during this period: an exceptional year for partnerships. Marriage is highly favored for singles, and existing relationships deepen with mutual respect. Business partnerships expand, and consulting or advisory work attracts quality clients. Public dealings go smoothly. Spouse may achieve something meaningful. Travel with partner is rewarding. Counselling, mediation and contracts all benefit from your presence; you become the wise voice in the room.",
        8: "Jupiter in Bhav 8 during this period: inheritance, insurance and joint finances bring positive surprises. Research, occult studies and deep philosophical work reach new levels. A long-held fear or trauma can be processed and released this year. Partner's income may rise. Avoid recklessness; even Jupiter can't fully soften this house's edges. Longevity-related practices like yoga, pranayama and dietary discipline yield disproportionate benefits now.",
        9: "Jupiter in Bhav 9 during this period: arguably the most powerful placement. Dharma, fortune, mentors and long journeys flourish. Pilgrimage, foreign travel for higher purpose, advanced studies and publishing all succeed. A guru's grace becomes tangible. Father's well-being or relationship with him improves. Legal matters tilt in your favor. Teaching, writing books and ethical leadership bring not just success but a deep sense of meaning.",
        10: "Jupiter in Bhav 10 during this period: career growth with reputation and respect. Promotions, awards and opportunities to lead with integrity arise. Roles in education, law, finance, consulting, religion or government flourish. Authorities recognize your judgment. Workload is manageable and meaningful rather than draining. A leadership role you accept now can become the defining chapter of your professional life — choose deliberately.",
        11: "Jupiter in Bhav 11 during this period: outstanding for gains, fulfilled wishes and powerful friendships. Income rises substantially, especially through advisory, teaching or finance-related work. Elder siblings prosper. A long-held wish materializes, often unexpectedly. Influential, ethical people enter your network. Group leadership and association memberships bring honor. Be discerning — even abundance asks you to choose where to direct it rather than spread thin.",
        12: "Jupiter in Bhav 12 during this period: spiritual depth, foreign opportunities and meaningful expenses. You may travel abroad for study, work or pilgrimage, or invest significantly in learning, charity or a parent's care. Sleep and dreams become rich and restorative. Donations made now return as unseen protection later. Solitary practice deepens; a retreat or extended quiet period can shift your inner landscape more than any external achievement.",
    },
    "Venus": {
        1: "Venus in Bhav 1 during this period: charm, beauty and magnetism rise. Appearance improves, social invitations multiply, and romantic prospects flourish. Artistic, fashion or design-related work shines. Comfort can tip into indulgence — watch weight, late nights and overspending on appearance. A new wardrobe, grooming routine or even a small cosmetic refresh feels natural now. People genuinely enjoy your company; use it for connection, not just attention.",
        2: "Venus in Bhav 2 during this period: wealth, family harmony and pleasures of the senses grow. Income rises through luxury goods, art, beauty, food, or finance-related fields. Family gatherings are warm, and a marriage or engagement in the family is likely. Speech becomes sweet and persuasive. Spending on jewelry, dining and home decor will tempt you — set a clear budget so the year's income translates into lasting savings.",
        3: "Venus in Bhav 3 during this period: pleasant short trips, creative writing and relationships with siblings improve. Marketing, design, content and artistic communication flourish. A sister or female peer becomes a meaningful ally. Romance has a playful, conversational quality. Self-promotion comes naturally. Avoid laziness disguised as easy charm; the year rewards consistent, light effort more than occasional bursts of brilliance — keep the small commitments you make.",
        4: "Venus in Bhav 4 during this period: home becomes more beautiful and harmonious. Vehicle purchase, interior upgrade or property acquisition is highly favored. Mother's well-being improves, and family relationships sweeten. Hosting, gardening and decorating bring real joy. A long-cherished dream of a comfortable, aesthetic home space can materialize. Real estate dealings, especially properties associated with luxury, leisure or culture, are particularly auspicious.",
        5: "Venus in Bhav 5 during this period: romance, children and creativity bloom. New love, deepening of existing relationships, or conception is highly likely. Children bring joy through artistic or romantic milestones. Higher learning in arts, design or culture flourishes. Speculative gains tied to entertainment or luxury are possible with restraint. Devotional practice through music, dance or chanting feels especially natural and effective this year.",
        6: "Venus in Bhav 6 during this period: a gentler year for handling enemies, debts and health. Conflicts soften through diplomacy. Loans can be cleared steadily, and workplace rivals turn into reluctant allies. Watch reproductive, urinary or kidney health; check-ups are wise. A pet may bring great joy or need care. Service through art, beauty or hospitality work flourishes. Indulgence in food and comfort needs gentle daily moderation.",
        7: "Venus in Bhav 7 during this period: an outstanding year for marriage and partnership. Singles often meet a significant partner; existing relationships rekindle warmth and intimacy. Business partnerships in luxury, art, fashion, beauty, hospitality or finance flourish. Public dealings go smoothly. Spouse may achieve something noteworthy. Travel together is rewarding. Avoid letting comfort breed complacency; small gestures and active appreciation keep the bond alive.",
        8: "Venus in Bhav 8 during this period: intense, transformative experiences in love, money and intimacy. Inheritance or partner's income may rise, often unexpectedly. Sexuality and emotional depth become more important than surface charm. Research into healing, occult or psychological work attracts you. Watch reproductive health and avoid risky financial entanglements. A relationship taken to deeper, more honest ground this year can become genuinely soul-level rather than just pleasant.",
        9: "Venus in Bhav 9 during this period: love, luck and long journeys to beautiful places. Foreign travel, often with partner or for cultural reasons, is highly favored. Higher studies in arts, hospitality or culture flourish. Mentors are often refined, artistic women. Father's well-being improves. Legal matters resolve diplomatically. Faith deepens through beauty — temple architecture, music, sacred art — rather than dry doctrine alone.",
        10: "Venus in Bhav 10 during this period: career growth in luxury, art, fashion, beauty, hospitality, entertainment, finance or design. Reputation grows for being elegant and effective rather than aggressive. Promotions and awards are likely. Female mentors or clients support your rise. Workplace becomes more aesthetic and pleasant. Public-facing roles flourish. Reputation is a real asset this year — protect it by under-promising and consistently over-delivering.",
        11: "Venus in Bhav 11 during this period: outstanding gains and fulfillment of cherished wishes. Income rises substantially through luxury, art, finance, fashion or social ventures. Influential, often female, friends actively support your goals. A long-held romantic or creative wish materializes. Group activities and high-end social circles open up. Be selective with who you let in; not every sparkling invitation serves your deeper goals for the year.",
        12: "Venus in Bhav 12 during this period: pleasures, foreign comforts and bedroom intimacy come forward. Foreign travel for leisure, romance or art is likely. Spending on luxury, comfort, beauty or a partner can spike. Privacy in relationships becomes important; secret romances are possible but risky. Sleep and dreams become richer. Charity through art or to women in need brings unseen blessings; meditation and gentle spiritual practice deepen.",
    },
    "Saturn": {
        1: "Saturn in Bhav 1 during this period: a sober, disciplined and weighty year. Responsibilities increase, you feel older than your years, and frivolous company falls away. Health needs steady routine — bones, joints, skin and chronic issues respond best to consistency. Professional reputation grows through reliability rather than charisma. A good year to commit to hard practice, rebuild a habit, or take on a serious responsibility you have been postponing.",
        2: "Saturn in Bhav 2 during this period: finances and family demand discipline. Income may grow slowly through hard work, while expenses test your planning. Speech becomes more measured — sometimes too restrained. Family conversations may carry old grievances; address them with patience. Watch teeth, eyes and digestion. A serious commitment to saving, budgeting or eliminating wasteful spending this year creates a foundation for the next several.",
        3: "Saturn in Bhav 3 during this period: an unexpectedly strong placement for Saturn. Sustained effort in writing, communication or skill-building pays off. Short journeys are tiring but productive. Relationships with siblings deepen through responsibility rather than fun. Courage shows up as endurance rather than impulse. Self-promotion through quiet credibility works far better than flash. Hands, shoulders and posture deserve regular care this year.",
        4: "Saturn in Bhav 4 during this period: home, mother and emotional comfort feel heavy. Family responsibilities increase and you may take on caregiving for a parent. Property matters drag on but eventually resolve. Mother's health needs attention. Watch for melancholy at home; a steady, simple routine helps. A move or renovation may be necessary rather than chosen. Long-term, the discipline this year demands creates real domestic stability.",
        5: "Saturn in Bhav 5 during this period: children, romance and creativity require patience. Children may face challenges that need your sustained support. Conception can be delayed; medical guidance helps. Higher studies progress slowly but solidly. Romance feels serious or strained. Speculation should be avoided. Disciplined creative practice — daily writing, daily art, daily study — produces work this year that you will be proud of for decades.",
        6: "Saturn in Bhav 6 during this period: an excellent placement. You will steadily defeat enemies, clear long-standing debts and recover from chronic ailments. Workload is heavy but rewarding, and discipline at the workplace earns respect. Lawsuits favor the patient side. Service-oriented roles flourish. Joints, knees and chronic conditions need ongoing care. Loans can be cleared faster than expected if you stay disciplined and avoid taking on new ones.",
        7: "Saturn in Bhav 7 during this period: partnerships demand maturity. Marriage is possible but to someone older, more serious or from a different background. Existing relationships are tested by responsibility rather than passion. Business partnerships work if grounded in clear contracts. Public dealings require patience. Spouse may carry a heavy load this year; share it. Long-distance or delayed connections can deepen meaningfully if you show up consistently.",
        8: "Saturn in Bhav 8 during this period: a slow, deep, transformative year. Inheritance, insurance or joint finances move slowly through bureaucracy but eventually resolve. Chronic conditions need patience. Research, occult studies and longevity-related practices yield deep results. Avoid risky travel and extreme sports. A long-buried fear or pattern can finally be processed with the help of a steady practice or a skilled practitioner.",
        9: "Saturn in Bhav 9 during this period: faith, fortune and father are tested through discipline. Long journeys may be tiring but meaningful — pilgrimage, work travel or relocation are likely. Higher studies progress steadily. Father may face health concerns. Legal matters drag on but tilt in your favor with patience. Teaching, ethical leadership and disciplined spiritual practice bring deeper rewards than easier years would have offered.",
        10: "Saturn in Bhav 10 during this period: a powerful career placement. Promotions, expanded responsibility and recognition for sustained effort are very likely. Roles in government, law, engineering, mining, real estate and traditional industries flourish. Workload is heavy and hours long; family time needs guarding. Reputation grows through reliability, not flash. A serious leadership role accepted now can define your professional identity for the next decade.",
        11: "Saturn in Bhav 11 during this period: steady, substantial gains through hard work and patient networking. Income rises through long-term commitments rather than quick wins. Elder siblings may need support or bring news of significant developments. Older, established friends become especially valuable. A long-held wish requiring patience finally fulfills. Group leadership in serious associations or causes is likely; be selective about commitments to avoid burnout.",
        12: "Saturn in Bhav 12 during this period: expenses, foreign matters and inner discipline rise. Spending on litigation, medical care or a parent can be heavy. Foreign relocation or extended travel for work is possible. Sleep needs attention; reduce stimulation in evenings. Solitary practice, meditation, retreat and serious spiritual study yield deep results. A quiet year of inner work this year sets up the visible breakthroughs of the years ahead.",
    },
    "Rahu": {
        1: "Rahu in Bhav 1 during this period: identity, ambition and image undergo a strange but powerful shift. You may chase unconventional goals, attract attention from unexpected quarters and feel pulled toward foreign or non-traditional paths. Health can feel inexplicable; favor grounding routines. Confidence is high but illusions are also strong. A good year to break out of an old self-image, provided you don't lose sight of what is genuinely yours.",
        2: "Rahu in Bhav 2 during this period: finances, family and speech swing dramatically. Sudden gains through unconventional means, foreign sources or technology are possible, alongside equally sudden expenses. Family dynamics shift, sometimes through a foreign or unusual element. Watch speech — half-truths catch up quickly. Investments in tech, crypto or speculative instruments can pay off but stay disciplined; what comes fast can also leave fast.",
        3: "Rahu in Bhav 3 during this period: usually a strong placement for Rahu. Bold initiatives, foreign communication, technology, social media and unconventional ventures flourish. Courage is high and you will take risks others wouldn't. A sibling may be involved in something unusual or far away. Self-promotion through digital and viral channels works well. Avoid burning bridges in the rush; some collaborators are worth keeping for later.",
        4: "Rahu in Bhav 4 during this period: home life and inner peace get unsettled. Possible relocation abroad, unusual property dealings or family secrets surfacing. Mother's health may be a concern. Vehicle changes, often impulsive, are likely. Watch dissatisfaction at home that is really restlessness inside. A foreign or unconventional approach to housing — co-living, remote work setup, rental abroad — can work surprisingly well this year.",
        5: "Rahu in Bhav 5 during this period: speculation, romance and children become unpredictable. Sudden gains through markets, crypto or risky ventures are possible but stay measured. Romance may involve someone foreign, unconventional or much younger or older than expected. Conception can be delayed or come unexpectedly. Children may take unusual paths. Devotional practice with mantra, especially for Rahu, helps stabilize the year's intensity.",
        6: "Rahu in Bhav 6 during this period: another strong placement. You will defeat enemies through unconventional means and clear debts in surprising ways. Workplace politics tilt in your favor if you stay alert. Watch for skin issues, mysterious ailments and anxiety. Service-oriented roles in foreign companies, tech or unconventional fields flourish. Lawsuits can be won through smart maneuvering rather than direct confrontation. Avoid manipulative tactics — they backfire.",
        7: "Rahu in Bhav 7 during this period: partnerships become unconventional and unpredictable. Marriage may be inter-cultural, long-distance or to someone unusual. Existing relationships face sudden shifts. Business partnerships with foreigners or in tech can succeed but require clear contracts. Public dealings demand caution against deception. Spouse's behavior may surprise you. Read every agreement twice; this is not the year for handshake deals or casual trust.",
        8: "Rahu in Bhav 8 during this period: a sensitive placement. Sudden financial events, inheritance disputes or unexpected losses are possible. Research, occult studies and investigation reach unusual depths. Watch for accidents, surgeries and risky travel. Joint finances need careful documentation. A long-buried truth — yours or others' — may surface. Insurance and medical check-ups are wise. Spiritual practice, especially mantra, provides genuine protection through the year.",
        9: "Rahu in Bhav 9 during this period: foreign travel, unconventional teachers and unusual philosophies attract you. Higher studies abroad, distance learning or non-traditional credentials work well. Father may face unexpected developments. Legal matters carry uncertainty; rely on documentation, not goodwill. Avoid getting drawn into cult-like groups or charismatic but shallow gurus. A genuine teacher, often from a foreign tradition, can offer something authentic this year.",
        10: "Rahu in Bhav 10 during this period: a powerful but volatile career placement. Sudden rise in status, unconventional career moves and visibility through foreign or technology-driven channels are likely. Promotions can come surprisingly fast. Watch for politics, scandals and overreach. Reputation is fragile — protect it actively. Roles in technology, foreign companies, media, aviation or unconventional fields flourish. Don't believe your own hype before the results land.",
        11: "Rahu in Bhav 11 during this period: typically excellent. Sudden gains, unexpected income streams and influential foreign or unconventional friends are very likely. Elder siblings may achieve something noteworthy. A long-held ambitious wish materializes through unusual channels. Group activities in tech, foreign or alternative spaces open up. Be discerning with new connections — not every charismatic newcomer to your circle has aligned interests with yours.",
        12: "Rahu in Bhav 12 during this period: foreign matters, hidden expenses and unusual inner experiences rise. Foreign travel, relocation or work for overseas clients is highly likely. Spending on travel, unusual interests or hidden matters can spike. Sleep becomes strange; vivid dreams need attention. Watch for hidden enemies and scams. Solitary spiritual practice, especially mantra and meditation, deepens significantly. Charity made discreetly returns multifold over time.",
    },
    "Ketu": {
        1: "Ketu in Bhav 1 during this period: identity feels detached, even uncertain. You may withdraw from social roles, question who you are, and feel pulled toward solitude or spirituality. Health can feel mysterious; favor gentle, grounding routines. Old ambitions lose their grip. A good year for inner work, retreat and dropping what no longer fits, even if external life looks momentarily quieter than usual to outsiders.",
        2: "Ketu in Bhav 2 during this period: finances and family feel less central, sometimes uncertain. Income may dip in some streams while opening unexpectedly in others. Family ties feel either deeper or more distant — rarely neutral. Speech becomes either profound or absent. Watch teeth, eyes and digestion. A simpler relationship with money and possessions this year, even if forced, often turns out to be a real blessing.",
        3: "Ketu in Bhav 3 during this period: courage takes a quieter, more spiritual form. You may take initiatives that look small but shift something deep. A sibling becomes more spiritual or distant. Short journeys may include pilgrimage. Communication becomes selective — fewer words, more meaning. Hands and shoulders need care. A skill or practice picked up almost accidentally now can become surprisingly central to your life later.",
        4: "Ketu in Bhav 4 during this period: home and emotional comfort feel less anchoring. You may detach from a property, vehicle or living situation. Mother's well-being may need attention. A spiritual atmosphere develops at home — meditation corner, simpler decor, fewer possessions. Watch sense of inner emptiness; it is asking for spiritual depth, not more stuff. Long-pending domestic clutter is best released this year, literally and emotionally.",
        5: "Ketu in Bhav 5 during this period: children, romance and creativity take a spiritual turn. Conception can be delayed; medical and prayerful approaches both help. Existing children may become more independent or distant. Romance feels less interesting than inner work. Speculation should be avoided — Ketu doesn't pay out reliably. Mantra, devotional practice and study of sacred texts feel unusually rewarding and natural this year.",
        6: "Ketu in Bhav 6 during this period: usually a strong placement. Enemies lose interest, debts dissolve unexpectedly and chronic conditions can heal in mysterious ways. Workplace conflicts fade rather than escalate. Watch for unusual ailments that mainstream medicine struggles with; alternative healing often works better here. Service to those in need, especially anonymously, brings real grace into your life. Lawsuits tend to settle out of court.",
        7: "Ketu in Bhav 7 during this period: partnerships feel strangely detached. Existing marriage may face emotional distance — patience and conscious presence help. Singles may meet someone briefly significant but transient. Business partnerships dissolve or transform. Public dealings feel less interesting. Spouse may turn spiritual or distant. A solo journey, retreat or quiet period in a partnership often deepens it more than any forced togetherness would.",
        8: "Ketu in Bhav 8 during this period: deep transformation, occult insight and detachment from material concerns. Inheritance or joint finances may resolve in unexpected ways. Research, healing and spiritual practice reach unusual depths. Watch for accidents and risky travel. A long-buried fear or trauma can finally be released, often through an unexpected catalyst. Longevity practices like yoga, pranayama and dietary discipline yield real results this year.",
        9: "Ketu in Bhav 9 during this period: faith deepens through experience rather than doctrine. Pilgrimage, meditation retreats and unconventional spiritual paths attract you. Higher studies in philosophy, theology or healing arts flourish. Father may turn spiritual or face health concerns. Legal matters resolve in unexpected ways. A genuine inner teacher — sometimes a book, sometimes a person you barely know — appears at exactly the right moment.",
        10: "Ketu in Bhav 10 during this period: career feels less compelling, even if outwardly successful. You may walk away from a role that no longer fits, or feel pulled toward purpose-driven, spiritual or healing work. Recognition comes in unusual ways. Watch for sudden career shifts that look risky but feel inwardly right. Reputation grows for depth and integrity rather than ambition; this is often quietly more valuable.",
        11: "Ketu in Bhav 11 during this period: gains feel less central, social circle thins and quality matters more than quantity. Income may shift toward purpose-driven streams. Elder siblings may become more spiritual or distant. A long-held material wish either fulfills in a transformed way or quietly loses its hold on you. Genuine, soul-level friendships deepen while superficial ones drift away with surprisingly little drama.",
        12: "Ketu in Bhav 12 during this period: arguably Ketu's best placement. Spiritual depth, foreign retreats, meditation and inner liberation reach new levels. Foreign travel often takes a spiritual or service-oriented form. Expenses on charity, retreat or healing rise but feel meaningful. Sleep becomes deeply restorative; dreams carry real insight. A quiet year of inner work this year often produces the spiritual breakthroughs of a lifetime.",
    },
}
